name: Deploy Monitoring
# memo test06-2
on:
  workflow_dispatch:
    inputs:
      env_name:
        description: 'environment name'
        required: true
        default: 'develop'
        type: choice
        options:
        - develop
        - prod
      tag:
        description: 'version tag'
        required: false
        default: ''

  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
      tag:
        type: string

permissions:
  id-token: write # use id-token(federation role)
  contents: read # use id-token(federation role)
  pull-requests: write
  issues: write

env:
  AWS_REGION: ap-northeast-1
  ROLE_TO_ASSUME_MEMBER: ${{ secrets.ROLE_TO_ASSUME_MEMBER }}
  ROLE_TO_ASSUME_SEC: ${{ secrets.ROLE_TO_ASSUME_SEC }}

jobs:
  cdk-deploy-actions:
    name: CDK Deploy Actions
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env_name }}
    steps:
      - name: Check
        shell: bash
        working-directory: ./
        run: |
          echo "${{ inputs.env_name }}: Deploy"
          echo "${{ env.ROLE_TO_ASSUME_MEMBER }}"
          echo "${{ env.ROLE_TO_ASSUME_SEC }}"
      