name: "Terraform Test: Env/Var/Sec for GitHub Actions Configs"

on:
  pull_request: {}
  workflow_dispatch: {}

permissions:
  id-token: write # use id-token(federation role)
  contents: read # use id-token(federation role)
  pull-requests: read

jobs:
  changed-check:
    runs-on: ubuntu-latest
    outputs:
      gh_actions_config: ${{ steps.filter.outputs.gh_actions_config }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Changed Files
        id: filter
        uses: dorny/paths-filter@v3
        with:
            list-files: json
            filters: |
              changed:
                - 'test1/**'
                - 'test2/**'

      - name: Changed Directories
        id: changes
        env:
          changed: ${{steps.filter.outputs.changed_files}}
        run: |
          projects="$( echo $changed | jq -r '.[]' | cut -d'/' -f2 | sort | uniq | jq -s -R -c 'split("\n") | map("apps/" + select(. != ""))' )"
          echo "projects=${projects}" >> $GITHUB_OUTPUT

  # terraform:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     gh_actions_config: ${{ steps.filter.outputs.gh_actions_config }}
  #   strategy:
  #       fail-fast: false
  #       matrix:
  #         directories:
  #           [
  #             test1,
  #             test2
  #           ]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Filter changes
  #       id: filter
  #       uses: dorny/paths-filter@v3
  #       with:
  #           list-files: json
  #           filters: |
  #             changed:
  #               - '${{matrix.directories}}/**/*.hcl'
  #               - '${{matrix.directories}}/**/*.tf'
  #               - '${{matrix.directories}}/**/*.tfvars'
  #               - '${{matrix.directories}}/**/*.yaml'
  #               - '${{matrix.directories}}/**/.terraform-version'