name: 'Terraform Test For PR'

on:
  pull_request: {}
  workflow_dispatch: {}

permissions:
  id-token: write # use id-token(federation role)
  contents: read # use id-token(federation role)
  pull-requests: read

jobs:
  changed-check:
    name: 'Terraform Test: Check Changed directories'
    runs-on: ubuntu-latest
    outputs:
      changed_directories: ${{ steps.changes.outputs.directories }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Changed Files
        id: filter
        uses: dorny/paths-filter@v3
        with:
            list-files: json
            filters: |
              changed:
                - 'gh_actions_config/**'
                - 'waf/**'

      - name: Changed Directories
        id: changes
        env:
          changed: ${{steps.filter.outputs.changed_files}}
        run: |
          targets="$( echo $changed | jq -r '.[]' | jq -s -R 'split("\n") | map(select(contains("/docs/") or contains("/Readme.md") | not))'  )"
          directories="$( echo $targets | jq -r '.[]' | cut -d'/' -f1 | sort -u | jq -s -R -c 'split("\n") | map(select(. != ""))' )"
          echo "directories=${directories}" >> $GITHUB_OUTPUT

  terraform-test:
    name: 'Terraform Test'
    needs: changed-check
    runs-on: ubuntu-latest
    if: needs.changed-check.outputs.changed_directories != '[]'
    strategy:
      matrix:
        directory: ${{ fromJSON(needs.changed-check.outputs.changed_directories) }}
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - name: TEST Echo
        run: |
          echo ${{ matrix.directory }}

      - name: Checkout
        uses: actions/checkout@v2

      # - name: Setup AWS Credentials
      #   uses: ./.github/actions/configure-aws-creds
      #   with:
      #     region: ${{ vars.REGION }}
      #     account_id: ${{ vars.ACCOUNT_ID }}
      #     role_name: ${{ env.ROLE_NAME }}

      # - name: Cache aqua tools
      #   id: cache-tools
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.local/share/aquaproj-aqua
      #     key: cache-tools-${{ hashFiles('aqua.yaml') }}
      # - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
      #   with:
      #     aqua_version: v2.30.0
     
      # - name: Change dir and get version
      #   id: get_version
      #   shell: bash
      #   run: |
      #     tf_version=$(cat .terraform-version)
      #     echo "tf_version=${tf_version}" >> "$GITHUB_OUTPUT"

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v2
      #   with:
      #     terraform_version: ${{ steps.get_version.outputs.tf_version }}

      # - name: Terraform Format
      #   run: terraform fmt -check

      # - name: Terraform Init
      #   run: terraform init -backend-config="bucket=idpf-ops-state-${{ vars.ACCOUNT_ID }}"

      # - name: Terraform Validate
      #   run: terraform validate -no-color

      # - name: 'Terraform Test: gh_actions_config'
      #   if: ${{ matrix.directory == 'gh_actions_config' }}
      #   uses: ./.github/actions/terraform-test-gh-actions-config

      # - name: 'Terraform Test: waf'
      #   if: ${{ matrix.directory == 'waf' }}
      #   uses: ./.github/actions/terraform-test-waf


  terraform-test-complete:
    name: 'Terraform Test: Completed'
    needs: terraform-test
    if: ${{ ! failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: completed
        run: |
          echo "Terraform Test Completed"
