name: 'Terraform Test For PR'

on:
  pull_request: {}
  workflow_dispatch: {}

permissions:
  id-token: write # use id-token(federation role)
  contents: read # use id-token(federation role)
  pull-requests: read

jobs:
  check_changed_directories:
    name: 'Terraform Test: Check Changed directories'
    runs-on: ubuntu-latest
    outputs:
      changed_directories: ${{ steps.changes.outputs.directories }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Changed Files
        id: filter
        uses: dorny/paths-filter@v3
        with:
            list-files: json
            filters: |
              test1:
                - 'test1/**'
              test2:
                - 'test2/**'

      - name: Changed Directories
        id: changes
        env:
          changed: ${{steps.filter.outputs.test1.changed_files}}
        run: |
          targets="$( echo $changed | jq -r '.[]' | jq -s -R 'split("\n") | map(select(contains("/docs/") or contains("/Readme.md") | not))'  )"
          directories="$( echo $targets | jq -r '.[]' | cut -d'/' -f1 | sort -u | jq -s -R -c 'split("\n") | map(select(. != ""))' )"
          echo "${changed}"
          echo "${directories}"
          echo "directories=${directories}" >> $GITHUB_OUTPUT

  terraform_test:
    name: Run Terraform Test
    needs: check_changed_directories
    if: needs.check_changed_directories.outputs.changed_directories != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJSON(needs.check_changed_directories.outputs.changed_directories) }}
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    environment: 
      name: develop

    steps:
      - name: Echo
        run: |
          echo "TEST"
